import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeContextProvider } from '@/context/ThemeContext'
import Navbar from '@/components/Navbar'
import ThemeProvider from '@/providers/ThemeProvider'
import Footer from '@/components/Footer'
import AuthProvider from '@/providers/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <ThemeContextProvider>
            <ThemeProvider>
              <div className='mx-auto px-10 bg-transparent xl:max-w-[1366px] lg:max-w-screen-lg lg:px-20 md:max-w-screen-md sm:max-w-screen-sm'>
                <Navbar />
                {children}
                <Footer />
              </div>
            </ThemeProvider>
          </ThemeContextProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
