import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import AuthProvider from '@/components/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head></head>
      <body className={inter.className}>
        <script
          dangerouslySetInnerHTML={{
            __html: `
            try {
              if (localStorage.getItem('dark')) {
                  document.body.classList.add('dark')
              } else {
                  document.body.classList.remove('dark')
              }
            } catch (_) {}
          `,
          }}
        ></script>
        <AuthProvider>
          <div className='flex flex-col justify-between mx-auto px-[60px] max-w-[1366px] min-h-screen'>
            <Navbar />
            {children}
            <Footer />
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
